# Generated by Django 2.1.8 on 2020-03-18 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activist',
            fields=[
                ('activist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='积极分子用户id编号')),
                ('activist_name', models.CharField(max_length=32, verbose_name='积极分子姓名')),
                ('activist_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=32, verbose_name='积极分子性别')),
                ('activist_phone', models.BigIntegerField(verbose_name='积极分子手机号码')),
                ('apply_date', models.DateField(verbose_name='积极分子申请入党日期')),
                ('voluntary_time', models.IntegerField(blank=True, null=True, verbose_name='志愿时长')),
                ('user_account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='积极分子用户对应账号信息外键')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='党务管理员id编号')),
                ('admin_name', models.CharField(max_length=32, verbose_name='党务管理员姓名')),
                ('admin_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=32, verbose_name='党务管理员性别')),
                ('admin_phone', models.CharField(max_length=32, verbose_name='党务管理员手机号码')),
                ('user_account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='党务管理员对应账号信息外键')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False, verbose_name='党员用户id编号')),
                ('member_name', models.CharField(max_length=32, verbose_name='党员用户姓名')),
                ('member_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=32, verbose_name='党员用户性别')),
                ('member_phone', models.BigIntegerField(verbose_name='党员用户手机号码')),
                ('first_date', models.DateField(verbose_name='入党日期')),
                ('member_status', models.CharField(choices=[('正式党员', '正式党员'), ('预备党员', '预备党员')], max_length=32, verbose_name='党员性质')),
                ('regular_date', models.DateField(blank=True, null=True, verbose_name='转正日期')),
                ('member_duty', models.CharField(choices=[('无', '无'), ('支部书记', '支部书记'), ('组织委员', '组织委员'), ('宣传委员', '宣传委员'), ('纪检委员', '纪检委员')], max_length=32, verbose_name='党员职务')),
                ('voluntary_time', models.IntegerField(blank=True, null=True, verbose_name='志愿时长')),
                ('in_date', models.DateField(blank=True, null=True, verbose_name='转入时间')),
                ('out_date', models.DateField(blank=True, null=True, verbose_name='转出时间')),
                ('is_in_team', models.CharField(choices=[('无', '无'), ('是', '是'), ('否', '否')], max_length=32, verbose_name='是否完成关系转入')),
                ('is_out_team', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=32, verbose_name='是否完成关系转出')),
                ('user_account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='党员用户对应账号信息外键')),
            ],
        ),
    ]
