# Generated by Django 2.1.8 on 2020-03-20 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardAndPunish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_1', models.TextField(max_length=256, verbose_name='奖励1级详细内容')),
                ('reward_2', models.TextField(max_length=256, verbose_name='奖励2级详细内容')),
                ('reward_3', models.TextField(max_length=256, verbose_name='奖励3级详细内容')),
                ('punish_1', models.TextField(max_length=256, verbose_name='惩罚1级详细内容')),
                ('punish_2', models.TextField(max_length=256, verbose_name='惩罚2级详细内容')),
                ('punish_3', models.TextField(max_length=256, verbose_name='惩罚3级详细内容')),
            ],
        ),
        migrations.CreateModel(
            name='RewardPunishInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_level', models.IntegerField(choices=[(0, '无奖励'), (1, '奖励1级'), (2, '奖励2级'), (3, '奖励3级')], verbose_name='奖励等级')),
                ('punish_level', models.IntegerField(choices=[(0, '无惩罚'), (1, '惩罚1级'), (2, '惩罚2级'), (3, '惩罚3级')], verbose_name='惩罚等级')),
                ('user_account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='奖惩对应账号信息外键')),
            ],
        ),
    ]
