# Generated by Django 2.1.8 on 2020-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rewardandpunish_rewardpunishinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpunishinfo',
            name='punish_level',
            field=models.IntegerField(choices=[(0, '无惩罚'), (1, '惩罚1级'), (2, '惩罚2级'), (3, '惩罚3级')], default=0, verbose_name='惩罚等级'),
        ),
        migrations.AlterField(
            model_name='rewardpunishinfo',
            name='reward_level',
            field=models.IntegerField(choices=[(0, '无奖励'), (1, '奖励1级'), (2, '奖励2级'), (3, '奖励3级')], default=0, verbose_name='奖励等级'),
        ),
    ]
