# Generated by Django 2.1.8 on 2020-03-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200320_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpunishinfo',
            name='user_account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Member', verbose_name='奖惩对应账号信息外键'),
        ),
    ]
