# Generated by Django 2.1.8 on 2020-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200320_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemocraticAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='会议日期')),
                ('title', models.CharField(max_length=128, verbose_name='会议标题')),
                ('attend_num', models.IntegerField(verbose_name='出勤人数')),
                ('absent_num', models.IntegerField(verbose_name='缺勤人数')),
                ('attendance', models.CharField(max_length=256, verbose_name='出勤名单')),
                ('absence', models.CharField(max_length=256, verbose_name='缺勤名单')),
            ],
        ),
    ]
