# Generated by Django 2.1.8 on 2020-03-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_democraticappraisal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_in_team',
        ),
        migrations.AddField(
            model_name='member',
            name='come_from_party',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='转入自什么组织'),
        ),
        migrations.AddField(
            model_name='member',
            name='leave_to_party',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='转出到什么组织'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_out_team',
            field=models.CharField(choices=[('是', '是'), ('否', '否'), ('转出待确认', '转出待确认')], max_length=32, verbose_name='是否完成关系转出'),
        ),
    ]
