# Generated by Django 2.1.8 on 2020-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200323_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardandpunish',
            name='regular_date_set',
            field=models.DateField(blank=True, null=True, verbose_name='转正日期'),
        ),
    ]
