# Generated by Django 2.1.8 on 2020-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rewardandpunish_regular_date_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardandpunish',
            name='first_date_set',
            field=models.DateField(blank=True, null=True, verbose_name='入党日期设置'),
        ),
        migrations.AlterField(
            model_name='rewardandpunish',
            name='regular_date_set',
            field=models.DateField(blank=True, null=True, verbose_name='转正日期设置'),
        ),
    ]
