# Generated by Django 2.1.8 on 2020-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200324_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_date_set', models.DateField(blank=True, null=True, verbose_name='转正日期设置')),
                ('first_date_set', models.DateField(blank=True, null=True, verbose_name='入党日期设置')),
                ('in_date_set', models.DateField(blank=True, null=True, verbose_name='转入日期设置')),
                ('out_date_set', models.DateField(blank=True, null=True, verbose_name='转出日期设置')),
            ],
        ),
        migrations.RemoveField(
            model_name='rewardandpunish',
            name='first_date_set',
        ),
        migrations.RemoveField(
            model_name='rewardandpunish',
            name='regular_date_set',
        ),
    ]
