# Generated by Django 2.1.8 on 2020-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200325_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='out_confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='转出确认时间'),
        ),
    ]
