# Generated by Django 2.1.8 on 2020-03-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_member_out_confirm_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='out_date',
        ),
    ]
