# Generated by Django 2.1.8 on 2020-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_member_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_date',
            field=models.DateField(blank=True, null=True, verbose_name='入党日期'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_duty',
            field=models.CharField(blank=True, choices=[('无', '无'), ('支部书记', '支部书记'), ('组织委员', '组织委员'), ('宣传委员', '宣传委员'), ('纪检委员', '纪检委员')], max_length=32, null=True, verbose_name='党员职务'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='党员用户手机号码'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.CharField(choices=[('正式党员', '正式党员'), ('预备党员', '预备党员')], max_length=32, verbose_name='政治面貌'),
        ),
    ]
