# Generated by Django 2.1.8 on 2020-03-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200325_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemocraticAppraisal',
            new_name='MeetingRecord',
        ),
    ]
