# Generated by Django 2.1.8 on 2020-03-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200326_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=64, verbose_name='组织名称')),
                ('party_duty', models.CharField(blank=True, choices=[('支部书记', '支部书记'), ('组织委员', '组织委员'), ('宣传委员', '宣传委员'), ('纪检委员', '纪检委员')], max_length=32, null=True, verbose_name='职务')),
                ('member_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Member', verbose_name='职务对应外键')),
            ],
        ),
    ]
