# Generated by Django 2.1.8 on 2020-03-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_partyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyinfo',
            name='member_account',
        ),
        migrations.RemoveField(
            model_name='partyinfo',
            name='party_duty',
        ),
        migrations.AddField(
            model_name='partyinfo',
            name='party_discipline',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='纪检委员'),
        ),
        migrations.AddField(
            model_name='partyinfo',
            name='party_organizer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='组织委员'),
        ),
        migrations.AddField(
            model_name='partyinfo',
            name='party_publicity',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='宣传委员'),
        ),
        migrations.AddField(
            model_name='partyinfo',
            name='party_secretary',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='支部书记'),
        ),
    ]
