# Generated by Django 2.1.8 on 2020-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200326_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='党课日期')),
                ('place', models.CharField(max_length=32, verbose_name='地点')),
                ('title', models.CharField(max_length=128, verbose_name='党课主题')),
                ('attend_num', models.IntegerField(verbose_name='出勤人数')),
                ('absent_num', models.IntegerField(verbose_name='缺勤人数')),
                ('attendance', models.CharField(max_length=256, verbose_name='出勤名单')),
                ('absence', models.CharField(max_length=256, verbose_name='缺勤名单')),
            ],
        ),
        migrations.AddField(
            model_name='meetingrecord',
            name='place',
            field=models.CharField(default='', max_length=32, verbose_name='地点'),
        ),
    ]
