# Generated by Django 2.1.8 on 2020-03-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200328_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyInfo',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False, verbose_name='活动报名id编号')),
            ],
        ),
        migrations.CreateModel(
            name='PartyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='活动主题')),
                ('time', models.DateField(verbose_name='活动日期')),
                ('place', models.CharField(max_length=32, verbose_name='活动地点')),
                ('content', models.TextField(verbose_name='活动内容')),
                ('apply_begin', models.DateField(verbose_name='活动报名起始日期')),
                ('apply_end', models.DateField(verbose_name='活动报名结束日期')),
                ('status', models.CharField(choices=[('报名未开始', '报名未开始'), ('报名中', '报名中'), ('报名结束', '报名结束'), ('活动已结束', '活动已结束')], max_length=32, verbose_name='活动状态')),
            ],
        ),
        migrations.AddField(
            model_name='applyinfo',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PartyActivity', verbose_name='活动id编号'),
        ),
        migrations.AddField(
            model_name='applyinfo',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Member', verbose_name='党员id编号'),
        ),
        migrations.AlterUniqueTogether(
            name='applyinfo',
            unique_together={('activity_id', 'member_id')},
        ),
    ]
