# Generated by Django 2.1.8 on 2020-04-03 10:47

import DjangoUeditor3.DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200330_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor3.DjangoUeditor.models.UEditorField(verbose_name='内容')),
            ],
        ),
    ]
