# Generated by Django 2.1.8 on 2020-04-05 08:34

import DjangoUeditor3.DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='Content',
            field=DjangoUeditor3.DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
    ]
