# Generated by Django 2.1.8 on 2020-04-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200405_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Content',
            new_name='content',
        ),
    ]
