# Generated by Django 2.1.8 on 2020-04-06 06:45

import DjangoUeditor3.DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200405_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor3.DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='partyactivity',
            name='content',
            field=DjangoUeditor3.DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
