# Generated by Django 2.1.8 on 2020-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200406_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyactivity',
            name='apply_begin',
            field=models.DateField(blank=True, null=True, verbose_name='活动报名起始日期'),
        ),
        migrations.AlterField(
            model_name='partyactivity',
            name='apply_end',
            field=models.DateField(blank=True, null=True, verbose_name='活动报名结束日期'),
        ),
    ]
