# Generated by Django 2.1.8 on 2020-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200406_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyinfo',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='applyinfo',
            old_name='member_id',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='partyactivity',
            name='status',
            field=models.CharField(choices=[('报名未开始', '报名未开始'), ('报名中', '报名中'), ('报名结束', '报名结束'), ('活动已结束', '活动已结束')], default='报名未开始', max_length=32, verbose_name='活动状态'),
        ),
        migrations.AlterUniqueTogether(
            name='applyinfo',
            unique_together={('activity', 'member')},
        ),
    ]
